### PR TITLE
Allow tracking composite widgets

### PR DESCRIPTION
**Pull request by svenefftinge**
I removed the EditorProvider from the editor manager in favor of adding a similar concept on the level of the focus tracker on the application shell.

### CODE REVIEW

**Review by vinokurig — APPROVED** [review]

**Comment by vinokurig** [comment]
@akosyakov WDYT?

**Comment by svenefftinge** [comment]
@vinokurig let me do a quick check before you are merging it.

**Review by akosyakov — APPROVED** [review]
LGTM

**Comment by svenefftinge** [comment]
Adjusted the stylings for active tabs, so that ...
screen shot 2018-08-06 at 14 41 16

**Comment by svenefftinge** [comment]
Done.

**Pull request merged**
